#!/usr/bin/expect -f
# wrapper to make "sudo usermod -aG $group $username" non-interactive
#
# Usage: ./adduser2group-onemachine $loginuser $password $username $group $serverid

set loginuser [lindex $argv 0]
set password [lindex $argv 1]
set username [lindex $argv 2]
set group [lindex $argv 3]
set serverid [lindex $argv 4]

spawn ssh $loginuser@$serverid
expect "password"
send "$password\r"
sleep 1
send "sudo /usr/sbin/usermod -aG $group $username\r"
expect "password"
send "$password\r"
send "exit\r"
expect eof
